name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - run: npm install
      - run: npm start